CREATE TABLE folders (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folder_name     TEXT NOT NULL
);

CREATE TABLE notes (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  note_name     TEXT NOT NULL,
  note_content  TEXT NOT NULL,
  modified      TIMESTAMP DEFAULT now() NOT NULL,
  created       TIMESTAMP DEFAULT now() NOT NULL,
  folder_id     INTEGER REFERENCES folders(id) ON DELETE CASCADE
);
